services:
  node-app:
    image: node
    working_dir: /app
    volumes:
      - ./app:/app
      - ./wait-for-it.sh:/wait-for-it.sh
    ports:
      - "3000:3000"
    command: ["sh", "-c", "/wait-for-it.sh db 3306 -- npm install express mysql2 && node app.js"]
    environment:
      MYSQL_HOST: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: mydb

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"